use_frameworks!

target 'BusinessZ_Example' do
  pod 'BusinessZ', :path => '../'

  target 'BusinessZ_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
